import Head from 'next/head';
import { useAppSelector } from '@/shared/lib/redux';
import { TodoItem } from '@/entities/todo';
import { PixiAssets } from '@/shared/constants/pixi';
import { PixiApp } from '@/widgets/pixiApp';
import { Background } from '@/features/background';
import { Platform } from '@/features/platform';
import { Ball } from '@/features/ball';
import styles from './BallPage.module.scss';

export default function BallPage() {
  const { currentTodo } = useAppSelector((state) => state.todo);
  const { assets } = useAppSelector((state) => state.pixi);

  return (
    <>
      <Head>
        <title>Ball</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.ballPage}>
        <PixiApp>
          {assets[PixiAssets.BACKGROUND] && <Background texture={assets[PixiAssets.BACKGROUND]} />}
          {assets[PixiAssets.PLATFORM] && <Platform texture={assets[PixiAssets.PLATFORM]} />}
          {assets[PixiAssets.BALL] && <Ball texture={assets[PixiAssets.BALL]} />}
        </PixiApp>
        {currentTodo && <TodoItem className={styles.todo} todo={currentTodo} />}
      </div>
    </>
  );
}
